name: Build

on:
  workflow_dispatch: {}
  push:
    branches:
      - '*'
    paths:
      - 'src/**'
jobs:
  build:
    name: Build binary
    runs-on: windows-2022
    strategy:
      matrix:
        configuration:
          - Release
    steps:
      - name: Check out files
        uses: actions/checkout@v3.5.2
        with:
          submodules: true
          fetch-depth: 0
          lfs: false

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Generate project files
        run: tools/premake5 vs2022

      - name: Set up problem matching
        uses: ammaraskar/msvc-problem-matcher@master

      - name: Build ${{matrix.configuration}}-binaries-rtx
        run: msbuild /m /v:minimal /p:Configuration=${{matrix.configuration}} /p:Platform=Win32 build/iw3sp_dev.sln

      - name: Move build files 
        run: |
          move build/bin/${{matrix.configuration}}/game.dll ./
          move build/bin/${{matrix.configuration}}/game.pdb ./
          
      - name: Upload ${{matrix.configuration}}-binaries-rtx
        uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.configuration}}-binaries-rtx
          path: |
            ./game.dll
            ./game.pdb
            ./assets-remix/*
